# Generated by Django 2.2.12 on 2020-04-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
